#!/usr/bin/env bash

set -e

if ! git show -s | grep -q '^Merge'; then
    echo "Not a merge commit"
    exit 0;
fi

for comp in  `ls components`; do
if ! git show --pretty="" --name-only | grep -q components/${comp}/idf_component.yml; then 
    echo "No changes in component version file"
    exit 0;
fi

version=`grep version: components/${comp}/.cz.yaml`
echo $version
version=${version#*version: }
echo $version

tag_format=`grep tag_format: components/${comp}/.cz.yaml`
echo $tag_format
tag_format=${tag_format:#*tag_format: }
echo $tag_format

eval tag=$tag_format
echo $tag

echo "BUMP_VERSION=${version}"
echo "BUMP_COMPONENT=${comp}"
echo "BUMP_TAG=${tag}"

echo "BUMP_VERSION=${version}" >> "$GITHUB_ENV"
echo "BUMP_COMPONENT=${comp}" >> "$GITHUB_ENV"
echo "BUMP_TAG=${tag}" >> "$GITHUB_ENV"

exit 0;

done
