name: Docs build

on:
  - push

jobs:
  docs_build:
    name: Docs-Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate docs
        run: |
          sudo apt-get update
          sudo apt-get -y install doxygen clang python3-pip
          python -m pip install breathe recommonmark
          cd $GITHUB_WORKSPACE/components/esp_modem/docs
          ./generate_docs
          cd $GITHUB_WORKSPACE/docs
          touch .nojekyll
          echo '<a href="esp_modem/index.html">esp-modem</a>' > index.html

      - name: Push to gh-pages
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Docs update per ${GITHUB_SHA} on `date`" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
